{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: food-order-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: food-order-strip-admin@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /admin/api
        pathType: Prefix
        backend:
          service:
            name: admin-backend
            port:
              number: 5000
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin-ui
            port:
              number: 80
      - path: /customer-api
        pathType: Prefix
        backend:
          service:
            name: customer-backend
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: customer-ui
            port:
              number: 80
{{- end }}